<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>disable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
		<Folder Include="ViewModel\" />
	</ItemGroup>

	<ItemGroup>
		<None Include="..\.editorconfig" Link=".editorconfig" />
		<None Include="..\OrderPoint.Admin\Components\Pages\Wholesaler\AppToast.razor" Link="AppToast.razor" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Blazor.Bootstrap" Version="3.3.1" />
		<PackageReference Include="Blazored.LocalStorage" Version="4.5.0" />
		<PackageReference Include="Blazored.Toast" Version="4.2.1" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.0" />
		<PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="9.0.0" />
		<PackageReference Include="Microsoft.Extensions.Http" Version="9.0.0" />
		<PackageReference Include="MudBlazor" Version="8.12.0" />
		<PackageReference Include="TinyMCE.Blazor" Version="2.1.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\OrderPoint.Domain\OrderPoint.Domain.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Content Update="Components\Common\LandingPageLoader.razor">
			<ExcludeFromSingleFile>true</ExcludeFromSingleFile>
		</Content>
		<Content Update="Components\Layout\AccountLayout\LogoutButton.razor">
			<ExcludeFromSingleFile>true</ExcludeFromSingleFile>
		</Content>
		<Content Update="Components\Pages\Account\ResetPassword.razor">
			<ExcludeFromSingleFile>true</ExcludeFromSingleFile>
		</Content>
		<Content Update="Components\Pages\Products\CustomerProdcutListing.razor">
			<ExcludeFromSingleFile>true</ExcludeFromSingleFile>
		</Content>
		<Content Update="Components\Pages\Wholesaler\DeliveryOptions.razor">
			<ExcludeFromSingleFile>true</ExcludeFromSingleFile>
		</Content>
		<Content Update="wwwroot\images\PlaceHolder.png">
			<ExcludeFromSingleFile>true</ExcludeFromSingleFile>
			<CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
		</Content>
	</ItemGroup>

</Project>